# Generated by Django 6.0 on 2026-01-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_manage_blog", "Может управлять блогом")],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
