# Generated by Django 6.0 on 2026-01-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"], "verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
    ]
