# Generated by Django 6.0 on 2026-01-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_options_remove_product_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Цена"),
        ),
    ]
